//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDogApp.AppResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XDogApp.AppResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string AddressAddress1 {
            get {
                return ResourceManager.GetString("AddressAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string AddressAddress2 {
            get {
                return ResourceManager.GetString("AddressAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 3.
        /// </summary>
        public static string AddressAddress3 {
            get {
                return ResourceManager.GetString("AddressAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 4.
        /// </summary>
        public static string AddressAddress4 {
            get {
                return ResourceManager.GetString("AddressAddress4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddressCity {
            get {
                return ResourceManager.GetString("AddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddressCountry {
            get {
                return ResourceManager.GetString("AddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode.
        /// </summary>
        public static string AddressPostCode {
            get {
                return ResourceManager.GetString("AddressPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string AddressTown {
            get {
                return ResourceManager.GetString("AddressTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BusinessBio {
            get {
                return ResourceManager.GetString("BusinessBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Incorporation.
        /// </summary>
        public static string BusinessDOB {
            get {
                return ResourceManager.GetString("BusinessDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Business.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Times.
        /// </summary>
        public static string BusinessOpeningTimes {
            get {
                return ResourceManager.GetString("BusinessOpeningTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string BusinessType {
            get {
                return ResourceManager.GetString("BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripton.
        /// </summary>
        public static string DogBio {
            get {
                return ResourceManager.GetString("DogBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed.
        /// </summary>
        public static string DogBreed {
            get {
                return ResourceManager.GetString("DogBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DogDOB {
            get {
                return ResourceManager.GetString("DogDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        public static string DogInterests {
            get {
                return ResourceManager.GetString("DogInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DogName {
            get {
                return ResourceManager.GetString("DogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address.
        /// </summary>
        public static string DogOwnerAddress {
            get {
                return ResourceManager.GetString("DogOwnerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Range.
        /// </summary>
        public static string DogOwnerAgeRangeMin {
            get {
                return ResourceManager.GetString("DogOwnerAgeRangeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Description.
        /// </summary>
        public static string DogOwnerBio {
            get {
                return ResourceManager.GetString("DogOwnerBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Country.
        /// </summary>
        public static string DogOwnerCountry {
            get {
                return ResourceManager.GetString("DogOwnerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DogOwnerCreate {
            get {
                return ResourceManager.GetString("DogOwnerCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Town.
        /// </summary>
        public static string DogOwnerCurrentTown {
            get {
                return ResourceManager.GetString("DogOwnerCurrentTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DogOwnerDOB {
            get {
                return ResourceManager.GetString("DogOwnerDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogs.
        /// </summary>
        public static string DogOwnerDogs {
            get {
                return ResourceManager.GetString("DogOwnerDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string DogOwnerEducation {
            get {
                return ResourceManager.GetString("DogOwnerEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DogOwnerEmailAddress {
            get {
                return ResourceManager.GetString("DogOwnerEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string DogOwnerFirstName {
            get {
                return ResourceManager.GetString("DogOwnerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Town.
        /// </summary>
        public static string DogOwnerHomeTown {
            get {
                return ResourceManager.GetString("DogOwnerHomeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        public static string DogOwnerInterests {
            get {
                return ResourceManager.GetString("DogOwnerInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string DogOwnerJob {
            get {
                return ResourceManager.GetString("DogOwnerJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string DogOwnerMobileNumber {
            get {
                return ResourceManager.GetString("DogOwnerMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Post Code.
        /// </summary>
        public static string DogOwnerPostCode {
            get {
                return ResourceManager.GetString("DogOwnerPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Dogs.
        /// </summary>
        public static string DogOwnerRelatedDogs {
            get {
                return ResourceManager.GetString("DogOwnerRelatedDogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Status.
        /// </summary>
        public static string DogOwnerRelationshipStatus {
            get {
                return ResourceManager.GetString("DogOwnerRelationshipStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Name.
        /// </summary>
        public static string DogOwnerScreenName {
            get {
                return ResourceManager.GetString("DogOwnerScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string DogOwnerSurname {
            get {
                return ResourceManager.GetString("DogOwnerSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string DogOwnerTelphoneNumber {
            get {
                return ResourceManager.GetString("DogOwnerTelphoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Place.
        /// </summary>
        public static string DogOwnerWorkPlace {
            get {
                return ResourceManager.GetString("DogOwnerWorkPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male or Female.
        /// </summary>
        public static string GenderDesc {
            get {
                return ResourceManager.GetString("GenderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey Distance.
        /// </summary>
        public static string JourneyDistance {
            get {
                return ResourceManager.GetString("JourneyDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey Time.
        /// </summary>
        public static string JourneyTime {
            get {
                return ResourceManager.GetString("JourneyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login.
        /// </summary>
        public static string LoginResponseDef {
            get {
                return ResourceManager.GetString("LoginResponseDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo.
        /// </summary>
        public static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Video.
        /// </summary>
        public static string PickVideo {
            get {
                return ResourceManager.GetString("PickVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string RegisterConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string RegisterLogin {
            get {
                return ResourceManager.GetString("RegisterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterRegister {
            get {
                return ResourceManager.GetString("RegisterRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Register.
        /// </summary>
        public static string RegisterResponseDef {
            get {
                return ResourceManager.GetString("RegisterResponseDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Verification Code.
        /// </summary>
        public static string RegisterSendVerificationCode {
            get {
                return ResourceManager.GetString("RegisterSendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string RegisterVerificationCode {
            get {
                return ResourceManager.GetString("RegisterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Video.
        /// </summary>
        public static string TakeVideo {
            get {
                return ResourceManager.GetString("TakeVideo", resourceCulture);
            }
        }
    }
}
